/* Main.c file generated by New Project wizard
 *
 * Created:   dom feb 25 2018
 * Processor: PIC18F4550
 * Compiler:  CCS for PIC
 */

#include <18F4550.h>

int main (void)
 { 
   // Write your code here
   while (1)
      ;
   return 0;
 }   
